version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.1
  env_file: .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./jobs:/opt/airflow/jobs
    - ./requirements.txt:/requirements.txt
  environment:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    PYTHONPATH: /opt/airflow
  depends_on:
    - postgres

services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create \
      --username admin \
      --firstname Admin --lastname User \
      --role Admin --email admin@example.com \
      --password admin"

  scheduler:
    <<: *airflow-common
    command: ["airflow", "scheduler"]

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]

volumes:
  postgres_db:
